name: Python-actions-sample
on: [push]
jobs:
  try-python:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files in the repository 
      run: |
        ls ${{ github.workspace }}

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Check Python version
      run: python --version

    # - name: Install dependencies
    #   run: pip install -r requirements.txt

    # - name: Run tests
    #   run: pytest
