
    # steps:name: Python-actions-sample
on: [push]
jobs:

  sample-job-1:
    name: Test Checkout
    runs-on: ubuntu-latest

    steps:
      - name: Set should_run Variable
        id: set_should_run
        run: echo "::set-output name=should_run::go"
  
      - name: Conditional Hello World
        if: steps.set_should_run.outputs.should_run == 'go'
        run: echo "Hello, World!"

    #   - name: Check Condition
    #     id: check_condition
    #     run: |
    #       should_run=true 
    #       echo " $should_run " 


    #   - name: echo World
    #     run: echo " ${{ steps.check_condition.outputs.should_run}} "

    #   - name: Conditional Hello World
    #     if: ${{ steps.check_condition.outputs.should_run == 'true' }}
    #     run: echo "Hello, World!"
