name: Python-actions-sample
on: [push]
jobs:

  sample-job-1:
    name: Test checks
    runs-on: ubuntu-latest
    
    steps:
      - name: prod-checks
        run: |
          echo "Deploying to production server on branch ${{ github.actor}} "


  sample-job-2:
    name: Test check
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'Sanmilee' }}

    steps:
      - name: prod-check
        run: |
          echo "Deploying to production server on branch $GITHUB_REF"

      - name: prod-check-2
        run: echo "Deploying to production server on behalf of $github.actor"
