name: Python-actions-sample
on: [push]
jobs:

  job-1:
    name: Test Checkout
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files in the repository 
        run: |
          ls ${{ github.workspace }}


  job-2:
    name: Test Python
    needs: job-1
    runs-on: windows-latest

    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Check Python version
        run: python --version
  
      
  job-3:
    name: Run Python Script
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run script
        run: python main.py
        
            
  job-4:
    name: Run Bash Script
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run bash script
        run: |
          # make test.sh executable
          chmod +x test.sh
          ./test.sh     
            