
    # steps:name: Python-actions-sample
on: [push]
jobs:

  sample-job-1:
    name: Test Checkout
    runs-on: ubuntu-latest

    steps:
      - name: Set color
        id: random-color-generator
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"

      - name: Get color
        env:
          SELECTED_COLOR: ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}
        run: echo "The selected color is $SELECTED_COLOR"
