name: Python-actions-sample
on: [push]
jobs:

  sample-job-1:
    name: Test check
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'octocat' }}
    # the 2 steps won'r run unless branch is main


    steps:
      - name: prod-check
        run: |
          echo "Deploying to production server on branch $GITHUB_REF"

      - name: prod-check-2
        run: echo "Deploying to production server on behalf of $github.actor"


  ample-job-1:
    name: Test checks
    runs-on: ubuntu-latest
    
    steps:
      - name: prod-checks
        run: |
          echo "Deploying to production server on branch $GITHUB_REF"
