name: Python-actions-sample
on: [push]
jobs:

  sample-job-1:
    name: Test Checkout
    runs-on: ubuntu-latest

    steps:
      - name: Check Branch Name
        id: branch_check
        run: echo "should_run=${{ github.ref == 'refs/heads/main' }}"
  
      - name: Conditional Hello World
        if: steps.branch_check.outputs.should_run == 'true'
        run: |
          echo "Hello, World!"


      # - name: Check Branch Name
      #   id: branch_check
      #   run: echo "::set-output name=should_run::${{ github.ref == 'refs/heads/main' }}"

      # - name: Conditional Hello World
      #   if: steps.branch_check.outputs.should_run == 'true'
      #   run: echo "Hello, World!"
