name: Python-actions-sample
on: [push]
jobs:
  example-job-1:
    name: Save output
    runs-on: ubuntu-latest

    steps:
      - name: create output log
        shell: bash
        run: |
          # set the result of 1 + 1 (2) into a log file
          expr 1 + 1 > output.log

      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file  # name of file
          path: output.log


  job-2:
    name: Download File
    needs: example-job-1
    runs-on: ubuntu-latest

    steps:
      - name: Download log file
        uses: actions/download-artifact@v3
        with:
          name: output-log-file

      - name: Print the final result
        shell: bash
        run: |
          value = `cat output.log`
          echo "The result is $value"
  
      
