# steps:

name: Python-actions-sample
on: [push]
jobs:

  sample-job-1:
    name: Test Checkout
    runs-on: ubuntu-latest

    steps:
      - name: Set and use a variable
        run: |
          MY_STEP_VARIABLE=green
          echo $MY_STEP_VARIABLE
