name: Python-actions-sample
on: [push]
jobs:

  sample-job-1:
    name: Test check
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - name: prod-check
        run: |
          echo "Deploying to production server on branch $GITHUB_REF"

      - name: prod-check-2
        run: |
          echo "Deploying to production server on branch $GITHUB_REF"
          