# steps:

name: Python-actions-sample
on: [push]


jobs:

  sample-job-1:
    name: Test Checkout
    runs-on: windows-latest

    steps:
      - run: dir
        if: runner.os == 'windows'  # ${{ runner.os == 'windows' }}


      - name: test env expression
        env:
          MY_ENV_VAR: ${{ github.ref == 'refs/heads/main' && 'for_main_branch' || 'other_branches' }}
          # MY_ENV_VAR is set to for_main_branch if branch is main, or other_branches if not
        run: echo $MY_ENV_VAR
