name: 'Link Checker: All English'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:



# This modifies the default permissions granted to `GITHUB_TOKEN`. 
# This will vary depending on the needs of your workflow. 
# For more info see "(/actions/using-jobs/assigning-permissions-to-jobs)."
# In this example, the `pull-requests: read` permission is needed for the `trilom/` action  
permissions:
  contents: read
  pull-requests: read


jobs:
  check-links:
    # Runs on 'self-hosted' runners if repo name == github/docs-internal, else runs on ubuntu runner
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install
        run: npm install -g bats


      - name: Run command
        run: bats -v


      # This step uses the `trilom/` action to gather all the changed files.  
      # This step creates the file "${{ env.HOME }}/files.json", among others.
      - name: Gather files changed
        uses: trilom/file-changes-action@a6ca26c14274c33b15e6499323aac178af06ad4b
        with:
          fileOutput: 'json'

      # To help with verification, this step lists the contents of `files.json`. 
      # This will be visible in the workflow run's log, and can be useful for debugging.
      - name: Show files changed
        run: cat $HOME/files.json
