name: Python-actions-sample
on: [push]

# This modifies the default permissions granted to `GITHUB_TOKEN`. 
# This will vary depending on the needs of your workflow. 
# For more info see "(/actions/using-jobs/assigning-permissions-to-jobs)."
# In this example, the `pull-requests: read` permission is needed for the `trilom/` action  
permissions:
  contents: read
  pull-requests: read



jobs:
  try-python:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3


    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'


    # - name: Install dependencies
    #   run: pip install -r requirements.txt

    - name: Run script
      run: | 
        python main.py
        python main.py --name Lee --age 5 --height 6.0


    # This step uses the `trilom/` action to gather all the changed files.  
    # This step creates the file "${{ env.HOME }}/files.json", among others.
    - name: Gather files changed
      uses: trilom/file-changes-action@a6ca26c14274c33b15e6499323aac178af06ad4b
      with:
        fileOutput: 'json'

    # To help with verification, this step lists the contents of `files.json`. 
    # This will be visible in the workflow run's log, and can be useful for debugging.
    - name: Show files changed
      run: cat $HOME/files.json
